//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moon.AspNetCore.Validation.Sample.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Pages_Home_FormModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Pages_Home_FormModel() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moon.AspNetCore.Validation.Sample.Resources.Pages.Home.FormModel", typeof(Pages_Home_FormModel).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The field &apos;{0}&apos; can only contain digits..
        /// </summary>
        public static string _Digits {
            get {
                return ResourceManager.GetString("_Digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The field &apos;{0}&apos; can only contain floating point number..
        /// </summary>
        public static string _Double {
            get {
                return ResourceManager.GetString("_Double", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The field &apos;{0}&apos; must contain a valid e-mail address..
        /// </summary>
        public static string _EmailAddress {
            get {
                return ResourceManager.GetString("_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The field &apos;{0}&apos; must be greater than the field &apos;{1}&apos;..
        /// </summary>
        public static string _GreaterThan {
            get {
                return ResourceManager.GetString("_GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The field &apos;{0}&apos; is required..
        /// </summary>
        public static string _Required {
            get {
                return ResourceManager.GetString("_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Digits.
        /// </summary>
        public static string Digits {
            get {
                return ResourceManager.GetString("Digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Double.
        /// </summary>
        public static string Double {
            get {
                return ResourceManager.GetString("Double", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please enter a floating point number..
        /// </summary>
        public static string Double_Double {
            get {
                return ResourceManager.GetString("Double_Double", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to EmailAddress.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to GreaterThanMin.
        /// </summary>
        public static string GreaterThanMin {
            get {
                return ResourceManager.GetString("GreaterThanMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to MightBeRequired.
        /// </summary>
        public static string MightBeRequired {
            get {
                return ResourceManager.GetString("MightBeRequired", resourceCulture);
            }
        }
    }
}
